Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using M7_Class_37_Work_01.Models;
using M7_Class_37_Work_01.Repositories;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
namespace M7_Class_37_Work_01.Controllers
{
    public class CoursesController : Controller
    {
        ICourseRepository repo;
        
        public CoursesController(ICourseRepository repo) {
            
            this.repo = repo;
                }
        public IActionResult Index(int page = 1, int tradeId=0)
        {
            var list = repo.GetTradesList();
            list.Insert(0, new Trade { TradeId = 0, TradeName = "All" });
            ViewBag.Trades = list;
            int pageSize = 5;
            var data = repo.GetWithChild();
            if(tradeId > 0)
            {
                return View(data.Where(x=> x.TradeId == tradeId).ToPagedList(page, pageSize));
            }
            return View(data.ToPagedList(page, pageSize));


        }
        public IActionResult Create()
        {
            var list = repo.GetTradesList();
            list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            return View();
        }
        public IActionResult GetCourseOptions(int id)
        {
            var data = repo.GetCourseOptions(id);
            data.Insert(0, new Course { CourseId = 0, CourseName = "Select" });
            return Json(data);
        }
        public IActionResult SaveStudents([FromBody]Student[] students)
        {
            if (ModelState.IsValid)
            {
                repo.InsertStudent(students);
                return Json(new { success = true, data = "Saved" });
            }
            return Json(new { success = false, data = "Error" });
        }
        public IActionResult CreateSingle( string postBack="")
        {
            var list = repo.GetTradesList();
            //list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            if(postBack != "")
            {
                ViewBag.PostBack = "Success";
            }
            return View();
        }
        [HttpPost]
        public IActionResult CreateSingle(Course c)
        {
            if (ModelState.IsValid)
            {
                if(repo.Insert(c))
                {
                    return RedirectToAction("CreateSingle", new { postBack = "postBack" });
                }
                
            }
            var list = repo.GetTradesList();
           // list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            return View(c);
        }
        public IActionResult EditSingle(int id, string postBack = "")
        {
            var list = repo.GetTradesList();
            //list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            if (postBack != "")
            {
                ViewBag.PostBack = "Success";
            }
            var data = repo.Get(id);
            return View(data);
        }
        [HttpPost]
        public IActionResult EditSingle(Course c)
        {
            if (ModelState.IsValid)
            {
                if (repo.Update(c))
                {
                    return RedirectToAction("EditSingle", new { postBack = "postBack" });
                }

            }
            var list = repo.GetTradesList();
            // list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            return View(c);
        }
        public IActionResult Edit(int id)
        {
            var list = repo.GetTradesList();
            //list.Insert(0, new Trade { TradeId = 0, TradeName = "Select" });
            ViewBag.Trades = list;
            var data = repo.GetWithChild(id);
            return View(data);
        }
        [HttpPost]
        public IActionResult SaveCourse([FromBody]Course c)
        {
            if (ModelState.IsValid)
            {
                repo.UpdateWithChild(c);
                    return Json(new { success = true });
            }
            return Json(new { success = false });
        }
        public IActionResult Delete(int id)
        {
            return View(repo.GetWithChild(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DoDelete(int id)
        {
            repo.Delete(id);
            return RedirectToAction("Index");
        }
    }
    
}

Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using M7_Class_37_Work_01.Models;
using M7_Class_37_Work_01.Repositories;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
namespace M7_Class_37_Work_01.Controllers
{
    public class StudentsController : Controller
    {
        IStudentRepository repo;
        public StudentsController(IStudentRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index(int page =1, int courseId=0)
        {
          
            var list = repo.GetCourseList();
            list.Insert(0, new Course { CourseId = 0, CourseName = "All" });
            ViewBag.Courses = list;
            int pageSize = 5;
            var data = repo.Get();
               
            if(courseId> 0)
            {
                return View(data.Where(s => s.CourseId == courseId).ToPagedList(page, pageSize));
            }
            return View(data.ToPagedList(page, pageSize));
        }
        public IActionResult Create(string postBack="")
        {
            var list = repo.GetCourseList();
            ViewBag.Courses = list;
            if(postBack!= "")
            {
                ViewBag.PostBack = "PostBack";
            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(Student s)
        {
            if (ModelState.IsValid)
            {
                if (repo.Insert(s))
                {
                    return RedirectToAction("Create", new { postBack = "PostBack" });
                }
            }
            var list = repo.GetCourseList();
            ViewBag.Courses = list;

            return View(s);
        }
        public IActionResult Edit(int id,string postBack = "")
        {
            var list = repo.GetCourseList();
            ViewBag.Courses = list;
            if (postBack != "")
            {
                ViewBag.PostBack = "PostBack";
            }
            var student = repo.Get(id);
            return View(student);
        }
        [HttpPost]
        public IActionResult Edit(Student s)
        {
            if (ModelState.IsValid)
            {
                if (repo.Update(s))
                {
                    return RedirectToAction("Edit", new {id=s.StudentId, postBack = "PostBack" });
                }
            }
            var list = repo.GetCourseList();
            ViewBag.Courses = list;
            
            
            return View(s);
        }
        public IActionResult Delete(int id)
        {
            return View(repo.GetWithParent(id));
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DoDelete(int id)
        {
            repo.Delete(id);
            return RedirectToAction("Index");
        }
        
    }
}

Controllers/TradesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using M7_Class_37_Work_01.Models;
using M7_Class_37_Work_01.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
namespace M7_Class_37_Work_01.Controllers
{
    //[Authorize]
    public class TradesController : Controller
    {
        ITradeRepo repo;
        public TradesController(ITradeRepo repo) { this.repo = repo; }
        public IActionResult Index(int page=1)
        {
            int size = 5;
            var data = repo.GetWithChildred()
                .ToPagedList(page, size);
           
            return View(data);
        }
        public IActionResult CreateTradeWithCourse()
        {
            return View();
        }
        public IActionResult CreateTradeWithCourse1()
        {
            return View();
        }
        [HttpPost]
        public JsonResult CreateTradeWithCourse([FromBody]Trade t)
        {
            if (ModelState.IsValid)
            {
                if (repo.Insert(t))
                    return Json(new { success = true });
                else
                    return Json(new { success = false });
            }
            else
            {
              return Json(new { success = false });
            }
            //return View();
        }
        public IActionResult GetCourseAddForm()
        {
            return PartialView("_CourseAddRowPartial");
        }
        public IActionResult Create(string postBack = "")
        {
            if (postBack != "")
            {
                ViewBag.PostBack = "Success";
            }
            return View();
        }
        [HttpPost]
        public IActionResult Create(Trade t)
        {
            if (ModelState.IsValid)
            {
                if (repo.Insert(t))
                {
                    return RedirectToAction("Create", new { postBack = "postBack" });
                }
            }
            return View(t);
        }
        public IActionResult EditWithCourse(int id)
        {
            var data = repo.Get(id);
            if (data == null)
                return NotFound();
            return View(data);
        }
        [HttpPost]
        public IActionResult EditWithCourse([FromBody]Trade t)
        {
            if (ModelState.IsValid)
            {
                repo.Update(t);
                return Json(new { success = true });
              
            }
            return Json(new { success = false });
            
        }
    }
}

Views/Trades/Create.cshtml
@model M7_Class_37_Work_01.Models.Trade

@{
    ViewData["Title"] = "Create";
}

<div class="card">
    <div class="card-header">
        <h4 class="card-title">Create Trade</h4>
    </div>
    <div class="card-body">
        @if (ViewBag.PostBack != null)
        {
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                <strong>Success!</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <p>Data Save Successfully.</p>
            </div>
        }
        <div class="card-text">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group row">
                    <label asp-for="TradeName" class="col-form-label col-2 text-right"></label>
                    <div class="col-4">
                        <input asp-for="TradeName" class="form-control" />
                        <span asp-validation-for="TradeName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-form-label col-2 text-right"></label>
                    <div class="col-4">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row form-check">
                    <label class="form-check-label col-4 offset-2">
                        <input class="form-check-input mt-2" asp-for="FemaleAllowed" /> @Html.DisplayNameFor(model => model.FemaleAllowed)
                    </label>
                </div>
                <div class="form-group row form-check">
                    <label class="form-check-label col-4 offset-2">
                        <input class="form-check-input mt-2" asp-for="IndustrialAttachment" /> @Html.DisplayNameFor(model => model.IndustrialAttachment)
                    </label>
                </div>

                <div class="form-group row">
                    <div class="col-4 offset-2">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>

                </div>
            </form>
        </div>
    </div>
    <div class="card-footer">
        <a asp-action="Index"><span class="fa fa-long-arrow-left"></span> Back to List</a>
    </div>
</div>


@section styles {

    <environment include="Development">
        <link href="~/libs/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/libs/gijgo/css/gijgo.css" rel="stylesheet" />
        <link href="~/libs/bs4-toast/toast.min.css" rel="stylesheet" />
    </environment>
}
@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/libs/bs4-toast/toast.min.js"></script>


}

Views/Trades/EditWithCourse.cshtml
@model Trade
@{
    ViewData["Title"] = "EditWithCourse";
}
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Edit Trade</h4>
    </div>
    <div class="card-body">
        <form asp-action="EditWithCourse" id="formTrade" name="formTrade">
            <h5 class="card-subtitle">Trade info</h5>
            <div class="card-text" id="part-trade">

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="TradeId" />
                <div class="form-group row">
                    <label asp-for="TradeName" class="col-form-label col-2 text-right"></label>

                    <div class="col-4">
                        <input asp-for="TradeName" class="form-control" />
                        <span asp-validation-for="TradeName" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <label asp-for="Description" class="col-form-label col-2 text-right"></label>

                    <div class="col-4">
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row form-check">
                    <label class="form-check-label col-4 offset-2">
                        <input class="form-check-input mt-2" asp-for="FemaleAllowed" /> @Html.DisplayNameFor(model => model.FemaleAllowed)
                    </label>
                </div>
                <div class="form-group row form-check">
                    <label class="form-check-label col-4 offset-2">
                        <input class="form-check-input mt-2" asp-for="IndustrialAttachment" /> @Html.DisplayNameFor(model => model.IndustrialAttachment)
                    </label>
                </div>


            </div>
            <h5 class="card-subtitle">Courses</h5>
            <div class="card-text" id="part-course">
                <table class="table table-bordered">

                    <thead>
                        <tr>
                            <th>Course Name</th>
                            <th>Duration</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var c in Model.Courses)
                        {
                            @await Html.PartialAsync("_EditCourseRow", c)
                        }
                    </tbody>
                </table>

            </div>
        </form>
    </div>
    <div class="card-footer">
        <div class="d-flex">
            <a asp-action="Index" asp-controller="Trades"><span class="fa fa-long-arrow-left"></span> Back to list</a>
            <button type="button" class="btn btn-primary btn-sm ml-auto" id="trade-finish">
                Update & Finish
            </button>
        </div>
    </div>
</div>


@section styles {

    <environment include="Development">
        <link href="~/libs/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <link href="~/libs/bs4-toast/toast.min.css" rel="stylesheet" />
    </environment>
}
@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/libs/bs4-toast/toast.min.js"></script>
    <script>
        $(document).ready(() => {
            $("button.del-course").click(function () {
                $(this).closest("tr").remove();
            })
            $("button#trade-finish").click(() => {
                console.log('ok');
                var valid = $("form#formTrade").valid();
                if (!valid) return;
                var data = {
                    Courses: []
                };
                data.TradeId = $("#TradeId").val();
                data.TradeName = $("#TradeName").val();
                data.Description = $("#Description").val();
                data.FemaleAllowed = $('input#FemaleAllowed').is(':checked');
                data.IndustrialAttachment = $('input#IndustrialAttachment').is(':checked');
                var names = $("input[name='CourseName']")
                var durations = $("input[name='Duration']")
                $.each($("input[name='CourseId']"), function (i, el) {
                    //console.log($(el).val());
                    //console.log($(names[i]).val());
                    //console.log($(durations[i]).val());
                    data.Courses.push({ CourseId: $(el).val(), CourseName: $(names[i]).val(), Duration: $(durations[i]).val() });
                });
                console.log(data);
                $.ajax({
                    type: "POST",
                    url: "/Trades/EditWithCourse",
                    contentType: "application/json",
                    dataType: "json",
                    data: JSON.stringify(data)
                }).done(r => {
                    console.log(r);
                    if (r.success == true) {
                        $.toast({
                            title: 'Success!',
                            subtitle: 'Saved',
                            content: 'Data saved successfully.',
                            type: 'success',
                            delay: 3000,
                            dismissible: true,

                            // is stackable?
                            stackable: true,
                            position: 'top-right'

                        });
                    }
                    else {
                        $.toast({
                            title: 'Error!',
                            subtitle: 'Failed.',
                            content: 'Data update failed.',
                            type: 'warning',
                            delay: 3000,
                            dismissible: true,

                            // is stackable?
                            stackable: true,
                            position: 'top-center bottom-right'

                        });
                    }
                }).fail(err => {
                    console.log(err);
                });
            });
        });
    </script>
}

Views/Trades/Index.cshtml
@model IEnumerable<Trade>

@{
    ViewData["Title"] = "Index";
}
@using X.PagedList
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Core.Fluent
@using X.PagedList.Web.Common
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Trades</h4>
        <div class="d-flex justify-content-end mb-1">
            <div class="btn-group">
                <button type="button" class="btn btn-danger">Action</button>
                <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="sr-only">Toggle Dropdown</span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <a class="dropdown-item" asp-action="Create" asp-controller="Trades">Create Trade</a>
                    <a class="dropdown-item" asp-action="CreateTradeWithCourse1" asp-controller="Trades">Create Trade with Course</a>
                    <a class="dropdown-item" asp-action="CreateSingle" asp-controller="Courses">Create Course</a>
                    <a class="dropdown-item" asp-action="Create" asp-controller="Courses">Create Course with Student</a>
                </div>
            </div>
        </div>
        <div class="card-text">
            <table class="table table-bordered">
                <thead class="thead-light">
                    <tr>
                        <th style="width:50px">
                            <button type="button" class="btn btn-sm all"><span class="fa fa-plus"></span></button>
                        </th>
                        <th>Trade ID</th>
                        <th>Trade Name</th>
                        <th>Female Allowed?</th>
                        <th>Requre IA?</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width:50px">
                                <button type="button" class="btn btn-sm trade" data-trade-pk="@item.TradeId"><span class="fa fa-plus-square"></span></button>
                            </td>
                            <td>@item.TradeId</td>
                            <td>@item.TradeName</td>
                            <td>@(item.FemaleAllowed ? "Yes" : "No")</td>
                            <td>@(item.IndustrialAttachment ? "Yes" : "No")</td>
                            <td>
                                <a asp-action="EditWithCourse" asp-controller="Trades" asp-route-id="@item.TradeId" class="btn btn-primary btn-sm rounded-circle"><span class="fa fa-pencil"></span></a>
                                <a asp-action="Delete" asp-controller="Trades" class="btn btn-danger btn-sm rounded-circle"><span class="fa fa-trash"></span></a>
                            </td>
                        </tr>
                        <tr style="display: none" id="trade-@item.TradeId" class="child-row">
                            <td></td>
                            <td colspan="5">
                                <table class="table table-bordered">
                                    <thead class="thead-light">
                                        <tr>
                                            <th style="width:50px">

                                            </th>
                                            <th>Course Name</th>
                                            <th>Duration (Hrs)</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var child in item.Courses)
                                        {
                                            <tr>
                                                <td>
                                                    <button type="button" class="btn btn-sm course" data-course-pk="@child.CourseId"><span class="fa fa-plus-square"></span></button>
                                                </td>
                                                <td>@child.CourseName</td>
                                                <td>@child.Duration</td>
                                                <td>
                                                    <a asp-action="EditSingle" asp-controller="Courses" asp-route-id="@child.CourseId" class="btn btn-primary btn-sm rounded-circle"><span class="fa fa-pencil"></span></a>


                                                    <a asp-action="Edit" asp-controller="Courses" asp-route-id="@child.CourseId" class="btn btn-secondary btn-sm rounded-circle"><span class="fa fa-pencil-square-o"></span></a>
                                                    <a asp-action="Delete" asp-controller="Courses" asp-route-id="@child.CourseId" class="btn btn-danger btn-sm rounded-circle"><span class="fa fa-trash"></span></a>
                                                </td>

                                            </tr>
                                            <tr style="display:none;" id="course-@child.CourseId" class="child-row">
                                                <td>&nbsp;</td>
                                                <td colspan="3">
                                                    <table class="table table-bordered">
                                                        <thead class="thead-light">
                                                            <tr>

                                                                <th>Student Name</th>
                                                                <th>Birth Date</th>
                                                                <th>E-mail</th>
                                                                <th></th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @foreach (var grand in child.Students)
                                                            {
                                                                <tr>

                                                                    <td>@grand.StudentName</td>
                                                                    <td>@grand.DOB.ToString("yyyy-MM-dd")</td>
                                                                    <td><a href="mailto:@grand.Email">@grand.Email</a></td>
                                                                    <td>
                                                                        <a asp-action="Edit" asp-controller="Students" asp-route-id="@grand.StudentId" class="btn btn-secondary btn-sm rounded-circle"><span class="fa fa-pencil"></span></a>
                                                                        <a asp-action="Delete" asp-controller="Students" asp-route-id="@grand.StudentId" class="btn btn-danger btn-sm rounded-circle"><span class="fa fa-trash"></span></a>
                                                                    </td>
                                                                  
                                                                </tr>
                                                            }
                                                        </tbody>
                                                    </table>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            
            <div class="d-flex justify-content-end">
                @(Html.Pager((IPagedList)Model)
                                        .Url(page => Url.Action("Index", "Trades", new { page = page }))
                                        .DisplayLinkToFirstPage(PagedListDisplayMode.IfNeeded)
                                        .DisplayLinkToLastPage(PagedListDisplayMode.IfNeeded)
                                        .DisplayLinkToPreviousPage()
                                        .DisplayLinkToNextPage()
                                        .MaximumPageNumbersToDisplay(3)
                                        .DisplayPageCountAndCurrentLocation(true)
                                        .Build()
                )
            </div>
            @*<div class="d-flex">
                @(Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page = page }), new PagedListRenderOptionsBase
                    {
                        PageClasses = new string[] { "page-link" },
                        UlElementClasses = new string[] { "pagination pagination-sm" },
                        LiElementClasses = new string[] { "page-item" },
                        DisplayItemSliceAndTotal = false,
                        DisplayLinkToFirstPage = PagedListDisplayMode.IfNeeded,
                        DisplayLinkToLastPage = PagedListDisplayMode.IfNeeded,
                        MaximumPageNumbersToDisplay = 3,
                        DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,
                        DisplayLinkToNextPage = PagedListDisplayMode.IfNeeded

                    })
                )
            </div>*@
        </div>
    </div>
    <div class="card-footer">


    </div>
</div>


@section styles{
    <environment include="Development">
        <link href="~/libs/PagedList/PagedList.css" rel="stylesheet" />
        <link href="~/libs/fontawesome/css/font-awesome.css" rel="stylesheet" />
        <script>
            $(document).ready(() => {
                $("button.trade").click(function () {
                    var id = $(this).data("trade-pk");
                    $("#trade-" + id).toggle();
                    $(this).find("span").toggleClass("fa-plus-square fa-minus-square");
                });
                $("button.course").click(function () {
                    var id = $(this).data("course-pk");
                    $("#course-" + id).toggle();
                    $(this).find("span").toggleClass("fa-plus-square fa-minus-square");
                });
                $("button.all").click(function () {
                    if ($(this).find("span").hasClass("fa-plus")) {
                        $("tr.child-row").show();
                        $("button.course span")
                            .removeClass("fa-plus-square")
                            .addClass("fa-minus-square");
                        $("button.trade span")
                            .removeClass("fa-plus-square")
                            .addClass("fa-minus-square");
                    }
                    else {
                        $("tr.child-row").hide();
                        $("button.course span").removeClass("fa-minus-square").addClass("fa-plus-square");
                        $("button.trade span").removeClass("fa-minus-square").addClass("fa-plus-square");
                    }
                    $(this).find("span").toggleClass("fa-plus fa-minus");
                })
            })
        </script>
    </environment>
}